name: End is Space
main: me.Codmikeg.endhelmet.endHelmet
version: 1.2
description: >
             End is now Space!.
commands:
  helmet:
    description: To apply your Space Helmet!
  h:
  	description: To apply your Space Helmet!
  test:
    description: testing